services:
  backend:
    container_name: banking_api_backend
    restart: always
    build: ./app
    ports:
      - 3333:3333
    networks:
    - banking_api_network
    environment:
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    depends_on:
      - database
    command: >
      sh -c "
      /wait && 
      yarn dev"
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
  database:
    container_name: banking_api_database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
    - banking_api_network
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: bankingapi
      POSTGRES_DATABASE: bankingapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
networks: 
  banking_api_network:
    driver: bridge